import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

// TODO: Continue implementing the Tic Tac Toe game

// 1. Do Dependency Injection for the widget
// 2. Use usescases to be called in the widget

/// This screen is the main entry point for the Tic Tac Toe game.
/// It allows the user to create a new game or join an existing one.
/// The user can enter a WebSocket URL to connect to the game server.
class TicTacToeScreen extends ConsumerStatefulWidget {
  const TicTacToeScreen({super.key});

  @override
  ConsumerState<ConsumerStatefulWidget> createState() =>
      _TicTacToeScreenState();
}

class _TicTacToeScreenState extends ConsumerState<TicTacToeScreen> {
  // Because this is a simple ws implementation the players names will be autogenerated
  final formKey = GlobalKey<FormState>();

  String webSocketHost = '';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Tic Tac Toe')),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: formKey,
          child: Column(
            children: [
              TextFormField(
                initialValue: 'ws://localhost:8080',
                decoration: const InputDecoration(labelText: 'WebSocket URL'),
                validator:
                    (value) => isValidWsUrl(value) ? null : 'Enter a valid URL. Example: ws://localhost:8080',
                onSaved: (value) => webSocketHost = value ?? '',
              ),
              const SizedBox(height: 60),
              ElevatedButton(
                onPressed: () {
                  if (formKey.currentState?.validate() == false) {
                    return;
                  }
                  formKey.currentState?.save();
                  log('Call to the server and navigate to the next screen $webSocketHost');
                },
                child: const Text('Create New Game'),
              ),
              const SizedBox(height: 30),
              ElevatedButton(
                onPressed: () {
                  // 1. Open a dialog that ask for the game id
                  // 2. Call the server to join the game
                  // 3. If the game / ws connection id is valid navigate to the game screen
                },
                child: const Text('Join Game'),
              ),
            ],
          ),
        ),
      ),
    );
  }

  bool isValidWsUrl(String? url) {
    if (url?.isEmpty ?? true) return false;

    final uri = Uri.tryParse(url!);
    if (uri == null) return false;

    final isWsScheme = uri.scheme == 'ws' || uri.scheme == 'wss';
    final hasHost = uri.host.isNotEmpty;

    return isWsScheme && hasHost;
  }
}
