// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV6KDcfpRfecg0rncDc0iE9faXXTe9dHk',
    appId: '1:92940279217:web:94725caffad6dfc344f190',
    messagingSenderId: '92940279217',
    projectId: 'rg-portfolio-70bdf',
    authDomain: 'rg-portfolio-70bdf.firebaseapp.com',
    storageBucket: 'rg-portfolio-70bdf.appspot.com',
    measurementId: 'G-RSXN1MRZB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAQDB5Y-xt8VGuRp3qBp-LkMgXIYRa0IE',
    appId: '1:92940279217:android:11e347b0abd2e59444f190',
    messagingSenderId: '92940279217',
    projectId: 'rg-portfolio-70bdf',
    storageBucket: 'rg-portfolio-70bdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjBwjQ8dI3kmTrQ8AslH3bDEcbmPj8VYs',
    appId: '1:92940279217:ios:d0c5297bf411d5d344f190',
    messagingSenderId: '92940279217',
    projectId: 'rg-portfolio-70bdf',
    storageBucket: 'rg-portfolio-70bdf.appspot.com',
    iosClientId: '92940279217-t787cftrggflat48an1010s8v8pf1il7.apps.googleusercontent.com',
    iosBundleId: 'com.rg.rgPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjBwjQ8dI3kmTrQ8AslH3bDEcbmPj8VYs',
    appId: '1:92940279217:ios:d0c5297bf411d5d344f190',
    messagingSenderId: '92940279217',
    projectId: 'rg-portfolio-70bdf',
    storageBucket: 'rg-portfolio-70bdf.appspot.com',
    iosClientId: '92940279217-t787cftrggflat48an1010s8v8pf1il7.apps.googleusercontent.com',
    iosBundleId: 'com.rg.rgPortfolio',
  );
}
